=== bmazou/data-formats/03-hierarchical/xml/schemas/schema-2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:foaf="https://xmls.com/foaf/0.1/">
<xs:import namespace="http://www.w3.org/XML/1998/namespace"
        schemaLocation="https://www.w3.org/2009/01/xml.xsd" />
    <xs:complexType name="langstring">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="Hospitals">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Hospital" maxOccurs="unbounded" minOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name"
                                        type="langstring" />
                            <xs:element name="address"
                                        type="langstring" />
                            <xs:element name="rooms">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Room"
                                                    minOccurs="0" maxOccurs="unbounded" >
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="number"
                                                                type="xs:int" />
                                                    <xs:element name="floor"
                                                                type="xs:int" />
                                                    <xs:element name="doctor" minOccurs="0" maxOccurs="1">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="firstName" 
                                                                            type="langstring"/>
                                                                <xs:element name="lastName" 
                                                                            type="langstring"/>
                                                                <xs:element name="degrees">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element name="degree"
                                                                                        type="langstring"
                                                                                        minOccurs="0"
                                                                                        maxOccurs="unbounded" />
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>  
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== bmazou/data-formats/03-hierarchical/xml/data/data-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Hospitals xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/schema-2.xsd">
    <Hospital>
        <name xml:lang="cs">Zlatá Nemocnice</name>
        <address xml:lang="cs">Československé armády 13, 160 00 Praha 6</address>
        <rooms>
            <Room>
                <number>110</number>
                <floor>0</floor>
                <doctor>
                    <firstName xml:lang="cs">Mantis</firstName>
                    <lastName xml:lang="cs">Toboggan</lastName>
                    <degrees>
                        <degree xml:lang="cs">MD</degree>
                    </degrees>
                </doctor>
            </Room>
            <Room>
                <number>120</number>
                <floor>0</floor>
                <doctor>
                    <firstName xml:lang="cs">Lyria</firstName>
                    <lastName xml:lang="cs">O'Lagalos</lastName>
                    <degrees>
                        <degree xml:lang="cs">MD</degree>
                        <degree xml:lang="cs">PhD</degree>
                    </degrees>
                </doctor>
            </Room>
        </rooms>
    </Hospital>
    <Hospital>
        <name xml:lang="cs">Červený Vrcholek</name>
        <address xml:lang="cs">Československé armády 13, 160 00 Praha 6</address>
        <rooms>
            <Room>
                <number>210</number>
                <floor>0</floor>
                <doctor>
                    <firstName xml:lang="cs">Milo</firstName>
                    <lastName xml:lang="cs">Minderbinder</lastName>
                    <degrees>
                        <degree xml:lang="cs">MPH</degree>
                    </degrees>
                </doctor>
            </Room>
            <Room>
                <number>221</number>
                <floor>1</floor>
                <doctor>
                    <firstName xml:lang="cs">Finree</firstName>
                    <lastName xml:lang="cs">Brock</lastName>
                    <degrees>
                        <degree xml:lang="cs">MD</degree>
                        <degree xml:lang="cs">MPH</degree>
                    </degrees>
                </doctor>
            </Room>
        </rooms>
    </Hospital>
    <Hospital>
        <name xml:lang="cs">Nová Šachta</name>
        <address xml:lang="cs">Budečská 933, 120 00 Praha 2</address>
        <rooms>
            <Room>
                <number>310</number>
                <floor>0</floor>
                <doctor>
                    <firstName xml:lang="cs">Mallet</firstName>
                    <lastName xml:lang="cs">Bridge</lastName>
                    <degrees>
                        <degree xml:lang="cs">MD</degree>
                    </degrees>
                </doctor>
            </Room>
            <Room>
                <number>321</number>
                <floor>1</floor>
            </Room>
        </rooms>
    </Hospital>
</Hospitals>
